function Leaderboard() {
  return (
    <>
      <div>
        <h1>Leaderboard</h1>
      </div>
      <table>
        <tr>
          <td>Rank</td>
          <td>Name</td>
          <td>HighScore</td>
          <td>Lives</td>
        </tr>
        <tr>
          <td>1</td>
          <td>Matthew</td>
          <td>123</td>
          <td>Lives</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Jolon</td>
          <td>123</td>
          <td>Lives</td>
        </tr>
        <tr>
          <td>3</td>
          <td>Tyler</td>
          <td>123</td>
          <td>Lives</td>
        </tr>
        <tr>
          <td>4</td>
          <td>Maitri</td>
          <td>123</td>
          <td>Lives</td>
        </tr>
        <tr>
          <td>5</td>
          <td>David</td>
          <td>123</td>
          <td>Lives</td>
        </tr>
      </table>
    </>
  )
}

export default Leaderboard
